planner_configs:
  RRTConnectkConfigDefault:
    type: geometric::RRTConnect
    range: 0.0  # Max step size, 0.0 means automatic
  PRMkConfigDefault:
    type: geometric::PRM
    max_nearest_neighbors: 10
  ESTkConfigDefault:
    type: geometric::EST
    goal_bias: 0.05

arm:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault
    - PRMkConfigDefault
    - ESTkConfigDefault
  projection_evaluator: joints(shoulder_joint,upper_arm_joint)
  longest_valid_segment_fraction: 0.005

gripper:
  default_planner_config: RRTConnectkConfigDefault
  planner_configs:
    - RRTConnectkConfigDefault