sensors:
  - camera_point_cloud
camera_point_cloud:
  sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
  # Gazebo'nun yeni nesil rgbd_camera sensörü point cloud'u otomatik olarak bu uzantıyla yayınlar:
  point_cloud_topic: /camera_head/points
  max_range: 1.5
  padding_offset: 0.03
  padding_scale: 1.0
  filtered_cloud_topic: filtered_cloud